exclude = [
    ".git",
    "__pycache__",
    "__init__.py",
    "setup.py",
]
line-length = 120

[lint]
ignore = [
    "B006",
    "B023",
    "D",
    "E501",
    "W605",
]
select = [
    "B",
    "D",
    "E",
    "F",
    "W",
]

[lint.pydocstyle]
convention = "numpy"

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
