site_name: FEMpy
site_description: Documentation for FEMpy
site_author: Ali Gray
site_url: https://a-cgray.github.io/FEMpy
repo_name: A-CGray/FEMpy
repo_url: https://github.com/A-CGray/FEMpy
theme:
    font:
        text: Open Sans
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.suggest
        - search.highlight
nav:
    - Home: index.md
    # - Elements:
    #      Generic Element: Elements/Element.md
    #      2D Quad: Elements/QuadElement.md
    #      Serendipity Quad: Elements/SerendipityQuad.md
    #      1D Line Element: Elements/Lagrange1dElement.md
    - Utilities:
        Linear Algebra: LinAlg/LinAlg.md
    - Contributing: DevelopmentGuide/DevelopmentGuide.md
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.progressbar
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        social_url_shorthand: True
        # more options on magiclink https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options
        provider: 'github'
    - codehilite:
        # https://help.farbox.com/pygments.html
        pygments_style: 'pastie'
        linenums: False
        # set to false to turn off pygments_style
        noclasses: False
    - pymdownx.tasklist
extra_javascript:
    - js/flowchart-loader.js
    - js/details.js
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.8.0/flowchart.min.js
extra_css:
    - css/progress_bar.css
    - css/details.css
    - css/tasklist.css
    - css/custom_tasklist.css
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: 'numpy'
                    show_if_no_docstring: True
