site_name: FEMpy
site_description: Documentation for FEMpy
site_author: Ali Gray
site_url: https://a-cgray.github.io/FEMpy
repo_name: A-CGray/FEMpy
repo_url: https://github.com/A-CGray/FEMpy
theme:
    font:
        text: Open Sans
    name: material
    icon:
        repo: fontawesome/brands/github
    palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.suggest
        - search.highlight
nav:
    - Home: index.md
    - Elements:
        Element Base Class: Elements/Element.md
        1D Line: Elements/Line1D.md
        2D Quad: Elements/Quad2D.md
        2D Tri: Elements/Tri2D.md
        3D Hex: Elements/Hex3D.md
    - Constitutive Models:
        Constitutive Model Base Class: ConstitutiveModels/ConstitutiveModel.md
        Isotropic 1D Elasticity: ConstitutiveModels/Iso1D.md
        Isotropic Plane Stress: ConstitutiveModels/IsoPlaneStress.md
        Isotropic Plane Strain: ConstitutiveModels/IsoPlaneStrain.md
        Isotropic 3D Elasticity: ConstitutiveModels/Iso3D.md
    - Contributing: DevelopmentGuide/DevelopmentGuide.md
    - Theory: Theory/Theory.md
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.progressbar
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        social_url_shorthand: True
        # more options on magiclink https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options
        provider: 'github'
    - codehilite:
        # https://help.farbox.com/pygments.html
        pygments_style: 'pastie'
        linenums: False
        # set to false to turn off pygments_style
        noclasses: False
    - pymdownx.tasklist
    - pymdownx.arithmatex:
        generic: true


extra_javascript:
    - js/flowchart-loader.js
    - js/details.js
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.8.0/flowchart.min.js
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
    - css/progress_bar.css
    - css/details.css
    - css/tasklist.css
    - css/custom_tasklist.css
plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                selection:
                    docstring_style: 'numpy'
                rendering:
                    show_if_no_docstring: True
