name: Formatting checks

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Download flake8 config
      run: wget https://raw.githubusercontent.com/mdolab/.github/master/.flake8;
    - uses: pre-commit/action@v2.0.3
