name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install coverage

    - name: Run unit tests
      run: testflo -n 1 -v .

    - name: Generate coverage report
      if: ${{ matrix.python-version == 3.12}}
      run: |
          export NUMBA_DISABLE_JIT=1
          testflo -n 1 -v --coverage --coverpkg FEMpy .
          coverage xml
    - name: Upload coverage reports to Codecov
      if: ${{ matrix.python-version == 3.12}}
      uses: codecov/codecov-action@v5.5.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
